### ISSUE TITLE
Bug: Tests column and main output area are empty

### ISSUE THREAD

**Issue by danieldunderfelt** [Raathigesh/majestic#2]
I pointed Majestic at a project that is built with Preact. Once I started Majestic and ran the test suite, I noticed the "Tests" column and the main output area were empty. The "Show all failures" also did nothing.

Screenshot:

https://imgur.com/a/9CzVY

Not sure what is causing this, and I tried restarting Majestic and re-opening the project several times. My Jest config:

```
"jest": {
    "collectCoverage": true,
    "coverageReporters": [ "html" ],
    "snapshotSerializers": [
      "jest-serializer-html-string"
    ]
  }
```
## Version Info

- Version of Majestic: 0.1.0
- Version of Jest: 21.1.0
- Version of Node: v8.8.1
- Operating System: macOS Sierra

**Comment by Raathigesh** [comment]
The default regex was not provided when it's not configured by the user.

**Comment by Raathigesh** [comment]
Should be fixed in https://github.com/Raathigesh/majestic/releases/tag/v0.2.0

**Comment by danieldunderfelt** [comment]
Hi!

Version 0.2.0 does not fix the main area being empty for me. It still is.

![](https://i.imgur.com/GETl4ba.png)

The Tests column seems to work however!

I modified the config a bit to try and get it to work, by adding the default regex and removing coverage settings, but to no avail.

**Comment by Raathigesh** [comment]
Hey @danieldunderfelt,

let me take a look. Sorry for the late reply. Was out of the country for a while.

**Comment by Raathigesh** [comment]
It's been a while 😅 but if you are still keen, the new shiny rewrite is available as an npm module. More info on readme -> https://github.com/Raathigesh/majestic/blob/next/README.md
